"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationforqueryentity import (
    ApplicationForQueryEntity,
    ApplicationForQueryEntityTypedDict,
)
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ApplicationForQueryListTypedDict(TypedDict):
    applications: List[ApplicationForQueryEntityTypedDict]


class ApplicationForQueryList(BaseModel):
    applications: List[ApplicationForQueryEntity]
