"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitytype import EntityType
from .person import Person, PersonTypedDict
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class BackendDataSchemaApplicationCreateEntityTypedDict(TypedDict):
    r"""Create application entity."""

    name: str
    entity_type: EntityType
    r"""Entity type."""
    label: str
    description: str
    purpose: str
    accountable_person: PersonTypedDict
    r"""Person entity."""
    business_impact: str


class BackendDataSchemaApplicationCreateEntity(BaseModel):
    r"""Create application entity."""

    name: str

    entity_type: EntityType
    r"""Entity type."""

    label: str

    description: str

    purpose: str

    accountable_person: Person
    r"""Person entity."""

    business_impact: str
