"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
import pydantic
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import FieldMetadata, MultipartFormMetadata
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ComputeFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class ComputeFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class BodyUpdateComputeFileAPIDataDataProductComputeFilePutTypedDict(TypedDict):
    compute_file: ComputeFileTypedDict


class BodyUpdateComputeFileAPIDataDataProductComputeFilePut(BaseModel):
    compute_file: Annotated[
        ComputeFile, FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ]
