"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ClassificationRegexRecognizerTypedDict(TypedDict):
    r"""Classification regex recognizer."""

    name: str
    description: str
    label: str
    patterns: List[str]


class ClassificationRegexRecognizer(BaseModel):
    r"""Classification regex recognizer."""

    name: str

    description: str

    label: str

    patterns: List[str]
