"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .runhistory import RunHistory, RunHistoryTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ComputeRunHistoryTypedDict(TypedDict):
    r"""Compute run history."""

    runs: List[RunHistoryTypedDict]


class ComputeRunHistory(BaseModel):
    r"""Compute run history."""

    runs: List[RunHistory]
