"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jobhistory import JobHistory, JobHistoryTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ComputeJobHistoryTypedDict(TypedDict):
    r"""Compute job history."""

    jobs: List[JobHistoryTypedDict]


class ComputeJobHistory(BaseModel):
    r"""Compute job history."""

    jobs: List[JobHistory]
