"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .assignee import Assignee, AssigneeTypedDict
from .entitytype import EntityType
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CreateMeshEntityTypedDict(TypedDict):
    r"""Create mesh entity."""

    name: str
    entity_type: EntityType
    r"""Entity type."""
    label: str
    description: str
    purpose: str
    assignees: List[AssigneeTypedDict]
    security_policy: List[str]


class CreateMeshEntity(BaseModel):
    r"""Create mesh entity."""

    name: str

    entity_type: EntityType
    r"""Entity type."""

    label: str

    description: str

    purpose: str

    assignees: List[Assignee]

    security_policy: List[str]
