"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class DataProductMeshAvailabilityRequestTypedDict(TypedDict):
    r"""Update data product available mesh"""

    mesh_identifier: str


class DataProductMeshAvailabilityRequest(BaseModel):
    r"""Update data product available mesh"""

    mesh_identifier: str
