"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .databasedatasourceconnectiondetails import (
    DatabaseDataSourceConnectionDetails,
    DatabaseDataSourceConnectionDetailsTypedDict,
)
from .entityinfo import EntityInfo, EntityInfoTypedDict
from .entitylinks import EntityLinks, EntityLinksTypedDict
from .entitywithowner import EntityWithOwner, EntityWithOwnerTypedDict
from .s3datasourceconnectiondetails import (
    S3DataSourceConnectionDetails,
    S3DataSourceConnectionDetailsTypedDict,
)
from .secret import Secret, SecretTypedDict
from .syntheticdatasourceconnectiondetails import (
    SyntheticDataSourceConnectionDetails,
    SyntheticDataSourceConnectionDetailsTypedDict,
)
from pydantic import Discriminator, Tag, model_serializer
from toan_fndtn.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from toan_fndtn.utils import get_discriminator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


DataSourceResponseConnectionTypedDict = TypeAliasType(
    "DataSourceResponseConnectionTypedDict",
    Union[
        SyntheticDataSourceConnectionDetailsTypedDict,
        S3DataSourceConnectionDetailsTypedDict,
        DatabaseDataSourceConnectionDetailsTypedDict,
    ],
)


DataSourceResponseConnection = Annotated[
    Union[
        Annotated[DatabaseDataSourceConnectionDetails, Tag("database")],
        Annotated[S3DataSourceConnectionDetails, Tag("s3")],
        Annotated[SyntheticDataSourceConnectionDetails, Tag("synthetic")],
    ],
    Discriminator(lambda m: get_discriminator(m, "connection_type", "connection_type")),
]


class DataSourceResponseTypedDict(TypedDict):
    r"""DataSource response."""

    entity: EntityWithOwnerTypedDict
    r"""Entity with owner."""
    links: EntityLinksTypedDict
    r"""Entity links."""
    entity_info: NotRequired[Nullable[EntityInfoTypedDict]]
    compute_identifier: NotRequired[Nullable[str]]
    secrets: NotRequired[List[SecretTypedDict]]
    connection: NotRequired[Nullable[DataSourceResponseConnectionTypedDict]]


class DataSourceResponse(BaseModel):
    r"""DataSource response."""

    entity: EntityWithOwner
    r"""Entity with owner."""

    links: EntityLinks
    r"""Entity links."""

    entity_info: OptionalNullable[EntityInfo] = UNSET

    compute_identifier: OptionalNullable[str] = UNSET

    secrets: Optional[List[Secret]] = None

    connection: OptionalNullable[DataSourceResponseConnection] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["entity_info", "compute_identifier", "secrets", "connection"]
        nullable_fields = ["entity_info", "compute_identifier", "connection"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
