"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DeduplicationKeep(str, Enum):
    r"""Deduplication keep."""

    FIRST = "first"
    LAST = "last"
