"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class EffectEnum(str, Enum):
    r"""Default effect enum for use with IAM actions."""

    ALLOW = "allow"
    DENY = "deny"
