"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class EntityType(str, Enum):
    r"""Entity type."""

    MESH = "mesh"
    DATA_SOURCE = "data_source"
    DATA_OBJECT = "data_object"
    DATA_PRODUCT = "data_product"
    APPLICATION = "application"
    DATA_SYSTEM = "data_system"
