"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorcode import ErrorCode, ErrorCodeTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ErrorCodesTypedDict(TypedDict):
    r"""Error codes."""

    errors: List[ErrorCodeTypedDict]


class ErrorCodes(BaseModel):
    r"""Error codes."""

    errors: List[ErrorCode]
