"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .optionalsparkconfig import OptionalSparkConfig, OptionalSparkConfigTypedDict
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class ExistingProductJobTypedDict(TypedDict):
    r"""ExistingProductJob model."""

    config: OptionalSparkConfigTypedDict
    r"""OptionalSparkConfig model."""


class ExistingProductJob(BaseModel):
    r"""ExistingProductJob model."""

    config: OptionalSparkConfig
    r"""OptionalSparkConfig model."""
