"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .expectation import Expectation, ExpectationTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ExpectationResultsTypedDict(TypedDict):
    r"""Expectation results."""

    results: List[ExpectationTypedDict]


class ExpectationResults(BaseModel):
    r"""Expectation results."""

    results: List[Expectation]
