"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .columntype import ColumnType
from toan_fndtn.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class FieldDataTypeTypedDict(TypedDict):
    r"""Field data type."""

    meta: Dict[str, str]
    column_type: ColumnType
    r"""Column type."""


class FieldDataType(BaseModel):
    r"""Field data type."""

    meta: Dict[str, str]

    column_type: ColumnType
    r"""Column type."""
