"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class JoinOperation(str, Enum):
    r"""Join operation."""

    INNER = "inner"
    LEFT = "left"
    RIGHT = "right"
    LEFT_ANTI = "left_anti"
    LEFT_SEMI = "left_semi"
    CROSS = "cross"
    SELF_JOIN = "self_join"
    OUTER = "outer"
    FULL = "full"
    FULLOUTER = "fullouter"
