"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class ManageRolePolicyTypedDict(TypedDict):
    role: str
    policy: str


class ManageRolePolicy(BaseModel):
    role: str

    policy: str
