"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class OverwritePartitionsConfigTypedDict(TypedDict):
    r"""Overwrite partitions configuration."""

    mode: Literal["overwrite_partitions"]


class OverwritePartitionsConfig(BaseModel):
    r"""Overwrite partitions configuration."""

    MODE: Annotated[
        Annotated[
            Literal["overwrite_partitions"],
            AfterValidator(validate_const("overwrite_partitions")),
        ],
        pydantic.Field(alias="mode"),
    ] = "overwrite_partitions"
