"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .replaceterm import ReplaceTerm, ReplaceTermTypedDict
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from toan_fndtn.utils import validate_const
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class PivotTransformationOutputAggregationsTypedDict(TypedDict):
    pass


class PivotTransformationOutputAggregations(BaseModel):
    pass


PivotTransformationOutputPivotValueTypedDict = TypeAliasType(
    "PivotTransformationOutputPivotValueTypedDict", Union[int, float, bool, str]
)


PivotTransformationOutputPivotValue = TypeAliasType(
    "PivotTransformationOutputPivotValue", Union[int, float, bool, str]
)


class PivotTransformationOutputTypedDict(TypedDict):
    r"""Pivot transformation."""

    input: str
    output: str
    group_columns: List[str]
    aggregations: PivotTransformationOutputAggregationsTypedDict
    pivot_column: str
    pivot_values: List[PivotTransformationOutputPivotValueTypedDict]
    transform: Literal["pivot"]
    pivot_values_changes: NotRequired[Nullable[List[ReplaceTermTypedDict]]]
    pivot_values_lowercase: NotRequired[bool]


class PivotTransformationOutput(BaseModel):
    r"""Pivot transformation."""

    input: str

    output: str

    group_columns: List[str]

    aggregations: PivotTransformationOutputAggregations

    pivot_column: str

    pivot_values: List[PivotTransformationOutputPivotValue]

    TRANSFORM: Annotated[
        Annotated[Literal["pivot"], AfterValidator(validate_const("pivot"))],
        pydantic.Field(alias="transform"),
    ] = "pivot"

    pivot_values_changes: OptionalNullable[List[ReplaceTerm]] = UNSET

    pivot_values_lowercase: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["pivot_values_changes", "pivot_values_lowercase"]
        nullable_fields = ["pivot_values_changes"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
