"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PrincipalsTypedDict(TypedDict):
    principals: List[str]


class Principals(BaseModel):
    principals: List[str]
