"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class ProfilingTypedDict(TypedDict):
    r"""Profiling."""

    id: str
    entity: str
    row_count: int
    column_count: int
    profile_sample: float
    column_stats: str
    created_at: datetime


class Profiling(BaseModel):
    r"""Profiling."""

    id: str

    entity: str

    row_count: int

    column_count: int

    profile_sample: float

    column_stats: str

    created_at: datetime
