"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RepartitionTransformationTypedDict(TypedDict):
    r"""Repartition transformation."""

    input: str
    output: str
    partition_columns: List[str]
    transform: Literal["repartition"]
    partition_num: NotRequired[int]


class RepartitionTransformation(BaseModel):
    r"""Repartition transformation."""

    input: str

    output: str

    partition_columns: List[str]

    TRANSFORM: Annotated[
        Annotated[
            Literal["repartition"], AfterValidator(validate_const("repartition"))
        ],
        pydantic.Field(alias="transform"),
    ] = "repartition"

    partition_num: Optional[int] = 1
