"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class ResetPasswordAPIIamPasswordResetPostRequestTypedDict(TypedDict):
    username: str


class ResetPasswordAPIIamPasswordResetPostRequest(BaseModel):
    username: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
