"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rolefullinfo import RoleFullInfo, RoleFullInfoTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class RolesInfoTypedDict(TypedDict):
    roles: List[RoleFullInfoTypedDict]


class RolesInfo(BaseModel):
    roles: List[RoleFullInfo]
