"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class RunHistoryTypedDict(TypedDict):
    r"""Run history."""

    created: datetime
    updated: datetime
    name: str
    status: str
    suffix: str
    run: str


class RunHistory(BaseModel):
    r"""Run history."""

    created: datetime

    updated: datetime

    name: str

    status: str

    suffix: str

    run: str
