"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


class SecretKeyTypedDict(TypedDict):
    access_key_id: str
    secret_access_key: str
    is_system: bool


class SecretKey(BaseModel):
    access_key_id: str

    secret_access_key: str

    is_system: bool
