"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class SelectColumnsTransformationTypedDict(TypedDict):
    r"""SelectColumnsTransformation model."""

    input: str
    output: str
    columns: List[str]
    transform: Literal["select_columns"]


class SelectColumnsTransformation(BaseModel):
    r"""SelectColumnsTransformation model."""

    input: str

    output: str

    columns: List[str]

    TRANSFORM: Annotated[
        Annotated[
            Literal["select_columns"], AfterValidator(validate_const("select_columns"))
        ],
        pydantic.Field(alias="transform"),
    ] = "select_columns"
