"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from toan_fndtn.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class SensitivityListResponseTypedDict(TypedDict):
    r"""Response schema for list of sensitivities."""

    sensitivities: List[Dict[str, str]]


class SensitivityListResponse(BaseModel):
    r"""Response schema for list of sensitivities."""

    sensitivities: List[Dict[str, str]]
