"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class SortTransformationOutputSortColumnsTypedDict(TypedDict):
    pass


class SortTransformationOutputSortColumns(BaseModel):
    pass


class SortTransformationOutputTypedDict(TypedDict):
    r"""Sort transformation."""

    input: str
    output: str
    sort_columns: SortTransformationOutputSortColumnsTypedDict
    transform: Literal["sort"]


class SortTransformationOutput(BaseModel):
    r"""Sort transformation."""

    input: str

    output: str

    sort_columns: SortTransformationOutputSortColumns

    TRANSFORM: Annotated[
        Annotated[Literal["sort"], AfterValidator(validate_const("sort"))],
        pydantic.Field(alias="transform"),
    ] = "sort"
