"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class SyntheticDataSourceConnectionDetailsTypedDict(TypedDict):
    r"""Synthetic data source connection details."""

    connection_type: Literal["synthetic"]


class SyntheticDataSourceConnectionDetails(BaseModel):
    r"""Synthetic data source connection details."""

    CONNECTION_TYPE: Annotated[
        Annotated[Literal["synthetic"], AfterValidator(validate_const("synthetic"))],
        pydantic.Field(alias="connection_type"),
    ] = "synthetic"
