"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToJSONStructTransformationTypedDict(TypedDict):
    r"""To JSON struct transformation."""

    input: str
    output: str
    alias: str
    columns: List[str]
    transform: Literal["to_json_struct"]
    ignore_null_fields: NotRequired[bool]


class ToJSONStructTransformation(BaseModel):
    r"""To JSON struct transformation."""

    input: str

    output: str

    alias: str

    columns: List[str]

    TRANSFORM: Annotated[
        Annotated[
            Literal["to_json_struct"], AfterValidator(validate_const("to_json_struct"))
        ],
        pydantic.Field(alias="transform"),
    ] = "to_json_struct"

    ignore_null_fields: Optional[bool] = False
