"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class ToStructTransformationTypedDict(TypedDict):
    r"""To struct transformation."""

    input: str
    output: str
    alias: str
    columns: List[str]
    transform: Literal["to_struct"]


class ToStructTransformation(BaseModel):
    r"""To struct transformation."""

    input: str

    output: str

    alias: str

    columns: List[str]

    TRANSFORM: Annotated[
        Annotated[Literal["to_struct"], AfterValidator(validate_const("to_struct"))],
        pydantic.Field(alias="transform"),
    ] = "to_struct"
