"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnionTransformationTypedDict(TypedDict):
    r"""Union transformation."""

    input: str
    output: str
    other: str
    transform: Literal["union"]
    allow_missing_columns: NotRequired[bool]


class UnionTransformation(BaseModel):
    r"""Union transformation."""

    input: str

    output: str

    other: str

    TRANSFORM: Annotated[
        Annotated[Literal["union"], AfterValidator(validate_const("union"))],
        pydantic.Field(alias="transform"),
    ] = "union"

    allow_missing_columns: Optional[bool] = False
