"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unixtimestampcolumn import UnixTimestampColumn, UnixTimestampColumnTypedDict
import pydantic
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import BaseModel
from toan_fndtn.utils import validate_const
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class UnixtimeToTimestampTransformationTypedDict(TypedDict):
    r"""Unixtime to Timestamp transformation."""

    input: str
    output: str
    changes: List[UnixTimestampColumnTypedDict]
    transform: Literal["unixtime_to_timestamp"]


class UnixtimeToTimestampTransformation(BaseModel):
    r"""Unixtime to Timestamp transformation."""

    input: str

    output: str

    changes: List[UnixTimestampColumn]

    TRANSFORM: Annotated[
        Annotated[
            Literal["unixtime_to_timestamp"],
            AfterValidator(validate_const("unixtime_to_timestamp")),
        ],
        pydantic.Field(alias="transform"),
    ] = "unixtime_to_timestamp"
