"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from toan_fndtn.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from toan_fndtn.utils import validate_const
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class UnpivotTransformationTypedDict(TypedDict):
    r"""Unpivot transformation."""

    input: str
    output: str
    unpivot_columns: List[str]
    name_column: str
    transform: Literal["unpivot"]
    values_column: NotRequired[Nullable[str]]


class UnpivotTransformation(BaseModel):
    r"""Unpivot transformation."""

    input: str

    output: str

    unpivot_columns: List[str]

    name_column: str

    TRANSFORM: Annotated[
        Annotated[Literal["unpivot"], AfterValidator(validate_const("unpivot"))],
        pydantic.Field(alias="transform"),
    ] = "unpivot"

    values_column: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["values_column"]
        nullable_fields = ["values_column"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
