"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .storeddataproductschema import (
    StoredDataProductSchema,
    StoredDataProductSchemaTypedDict,
)
from toan_fndtn.types import BaseModel
from typing_extensions import TypedDict


DetailsTypedDict = StoredDataProductSchemaTypedDict


Details = StoredDataProductSchema


class UpdateDataProductSchemaTypedDict(TypedDict):
    r"""Update data product schema."""

    details: DetailsTypedDict


class UpdateDataProductSchema(BaseModel):
    r"""Update data product schema."""

    details: Details
