"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class UsersTypedDict(TypedDict):
    users: List[UserTypedDict]


class Users(BaseModel):
    users: List[User]
