"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .validation import Validation, ValidationTypedDict
from toan_fndtn.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ValidationResultsTypedDict(TypedDict):
    r"""Validation results."""

    results: List[ValidationTypedDict]


class ValidationResults(BaseModel):
    r"""Validation results."""

    results: List[Validation]
